permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: Jeff Gao
  email: strivek@icloud.com

# 站点信息
title: strivek的blog
description: My personal blog
rss_url: /pages/atom.xml
baseurl: /blog
# gavatar头像及Favicon
gavatar: /blog/public/img/icon/head.png
favicon: /blog/public/img/icon/head.png





# 主题设置，自动激活某个标签
active: 读书

# 首页除了最新文章外显示分类
# cates: 
#   - Optimization
#   - LaTeX

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档

gems: [jekyll-paginate]

redcarpet:
  extensions: []
sass:
  sass_dir: public/css/bootstrap/
  style: compressed

comments :
    provider : duoshuo
    duoshuo : 
      short_name : havee
